booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    # Inquiry page Url
    path('', views.booking_form, name='booking_url'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

import home

urlpatterns = [
    # Admin site URL
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('inquiry/', include('inquiry.urls', namespace='inquiry')),
    path('locator/', include('locator.urls', namespace='locator')),
    path('gallery/', include('gallery.urls', namespace='gallery'))
]

# Serve media files during development from DJANGO server (this will be done with a web server on production)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    # Gallery page Url
    path('', views.gallery_index, name='gallery_url'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    # Main Page Url
    path('', views.home_index, name='home')
]

inquiry/urls.py
from django.urls import path
from . import views

app_name = 'inquiry'

urlpatterns = [
    # Inquiry page Url
    path('', views.inquiry_form, name='inquiry_url'),
    path('submit-inquiry', views.submit_form, name="submit_inquiry_url")
]

locator/urls.py
from django.urls import path
from . import views

app_name = 'locator'

urlpatterns = [
    # Menu Page Url
    path('', views.locator_index, name='locator_url'),
]

gallery/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class GalleryImage(models.Model):
    """
    Represents an Image in the gallery module.
    """
    image_title = models.CharField(
        max_length=250, help_text="Image Title")
    description = models.TextField(
        default="", blank=True, help_text="Description of the product")
    image = models.ImageField(
        upload_to='gallery/images', default='images/default-image.png')

    class Meta:
        # Display name for the model in plural form
        verbose_name_plural = 'Gallery Images'

    def __str__(self):
        # String representation of the product (its title)
        return self.image_title

    def get_absolute_url(self):
        return reverse("model_detail", kwargs={"pk": self.pk})

inquiry/models.py
from django.db import models
from django.utils import timezone


class InquiryForm(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20, default='N/A')
    email = models.EmailField(max_length=255, default='example@example.com')
    subject = models.CharField(max_length=10)
    special_requests = models.TextField(blank=True, null=True)
    date_time_sent = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Inquiry - {self.first_name} - {self.last_name} - {self.date_time_sent}"

locator/models.py
from django.db import models

# Create your models here.

inquiry/forms.py
# forms.py
from django import forms
from .models import InquiryForm


class ContactForm(forms.ModelForm):
    class Meta:
        model = InquiryForm
        fields = ['first_name', 'last_name',
                  'phone_number', 'email',
                  'subject', 'special_requests']
        # Exclude the time_sent field from the form
        exclude = ['time_sent', 'date_sent']

gallery/views.py
from django.shortcuts import render
from .models import GalleryImage
from django.core.paginator import Paginator


def gallery_index(request):
    """
    View function for rendering the gallery page.
    """
    items = GalleryImage.objects.all()  # Query all items from your model
    paginator = Paginator(items, 6)  # Show 9 items per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'items': items, 'page_obj': page_obj}

    # Render the HTML template
    return render(request, 'gallery/gallery.html', context)

home/views.py
from django.shortcuts import render


def home_index(request):
    """
    View function for rendering the home page.
    """
    # Render the HTML template with the provided context
    return render(request, 'home/home.html')

inquiry/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages
from .models import InquiryForm
from django.urls import reverse
from django.core.mail import EmailMessage
from django.template.loader import render_to_string


def inquiry_form(request):
    """
    View function for displaying the Inquiry Form.
    """
    return render(request, 'inquiry/inquiry-form.html')


def submit_form(request):
    if request.method == 'POST':
        first_name = request.POST.get('first-name')
        last_name = request.POST.get('last-name')
        phone_number = request.POST.get('phone-number')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        special_requests = request.POST.get('special-requests')

        # Collect form data
        form_data = InquiryForm(
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            email=email,
            subject=subject,
            special_requests=special_requests
        )

        try:
            # Save the form data
            form_data.save()

            # Send confirmation email
            send_confirmation_email(
                user_name=f"{first_name} {last_name}",
                user_email=email,
                subject=subject)

            # Send notification email to Administrator
            send_notification_email(
                first_name=first_name,
                last_name=last_name,
                user_email=email,
                subject=subject,
                special_requests=special_requests)

            # Add a success message
            messages.success(
                request=request,
                message=f'Thank you for your message! Please check your email for a confirmation.')

            # Redirect to the inquiry form page
            return HttpResponseRedirect(reverse('inquiry:inquiry_url'))
        except Exception as e:
            # Handle exceptions and show an error message
            messages.error(request, f'Whoops! An error occurred.')

    # Render the form page for GET requests or if form submission fails
    return render(request, 'inquiry/inquiry-form.html')


def send_confirmation_email(user_name, user_email, subject):
    """
    Send a confirmation email to the user based on the subject.
    """
    subject_to_template_mapping = {
        'General': 'inquiry/email_templates/email_confirmation_general.html',
        'Catering Request': 'inquiry/email_templates/email_confirmation_catering.html',
        'Feedback': 'inquiry/email_templates/email_confirmation_feedback.html',
        'Other': 'inquiry/email_templates/email_confirmation_other.html'
    }

    email_subject = 'Thank you for your message!'
    from_email = 'mikecarbonari1@gmail.com'
    template_name = subject_to_template_mapping.get(subject)
    context = {'user_name': user_name}
    message = render_to_string(
        f'{template_name}', context)

    email = EmailMessage(email_subject, message, from_email, [user_email])
    email.content_subtype = 'html'
    email.send(fail_silently=False)


def send_notification_email(first_name, last_name, user_email, subject, special_requests):
    """
    Send a notification email to the administrator.
    """
    email_subject = f'You have a new {subject} Message'
    from_email = 'mikecarbonari1@gmail.com'
    context = {
        'first_name': first_name,
        'last_name': last_name,
        'user_email': user_email,
        'subject': subject,
        'special_requests': special_requests
    }
    message = render_to_string(
        'inquiry/email_templates/email_notification.html', context)

    email = EmailMessage(email_subject, message, from_email, [
                         "tailoreddonuts@gmail.com"])
    email.content_subtype = 'html'
    email.send(fail_silently=False)

locator/views.py
from django.shortcuts import render

# Create your views here.


def locator_index(request):
    """
    view function for displaying the Locator page
    """
    return render(request, 'locator/locator.html')

booking/templates/booking/booking-form.html
{% extends "snippets/base.html" %}
{% load static %}
{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'booking/css/booking-form.css' %}" />
{% endblock cssfiles %}
{% block content %}
    <div class="container form-container">
        <h1>Booking.</h1>
        <hr class="thin-horizontal-line" />
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1" class="required-field">Contact details of the person ordering</label>
                <input type="tel"
                       class="form-control"
                       id="phone"
                       placeholder="Phone Number"
                       pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
                       title="Enter a valid phone number (XXX-XXX-XXXX)"
                       required />
                <!-- Optional: Add a small text below the input for additional instructions or validation messages -->
                <small id="phoneHelp" class="form-text text-muted">Enter your phone number in the format XXX-XXX-XXXX.</small>
                <div class="invalid-feedback">Please enter a valid phone number in the format XXX-XXX-XXXX.</div>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1" class="required-field">Number of Guests</label>
                <input class="form-control"
                       type="number"
                       id="quantity"
                       name="quantity"
                       min="1"
                       max="200"
                       placeholder="Number of people being catered for"
                       required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock content %}

contact/templates/inquiry-form.html
{% extends "./base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="text-center mb-4">Contact Us</h2>
                <form>
                    <div class="form-group">
                        <label for="name">Your Name</label>
                        <input type="text"
                               class="form-control"
                               id="name"
                               placeholder="Enter your name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email"
                               class="form-control"
                               id="email"
                               placeholder="Enter your email">
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone Number</label>
                        <input type="tel"
                               class="form-control"
                               id="phone"
                               placeholder="Enter your phone number">
                    </div>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <textarea class="form-control"
                                  id="message"
                                  rows="4"
                                  placeholder="Enter your message"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

gallery/templates/gallery/gallery.html
{% extends "snippets/base.html" %}
{% load static %}
{% block cssfiles %}
    <!-- Include CSS files specific to this page -->
    <link rel="stylesheet" href="{% static 'gallery/css/gallery.css' %}" />
{% endblock cssfiles %}
{% block content %}
    <!-- Main content of the gallery page -->
    <div class="gallery-container">
        <div class="container">
            <!-- Gallery title and description -->
            <h1 class="fw-light text-center">Captured Moments</h1>
            <div class="font-italic fw-light text-center lh-md">Immerse yourself in tasty delights!</div>
            <hr>
            <!-- Modal for displaying full images -->
            <div class="modal-container inactive" id="modal">
                <div class="modal-content">
                    <!-- Close button for the modal -->
                    <span class="close" id="closeModalButton">&times;</span>
                    <!-- Full image displayed in the modal -->
                    <img id="fullImage" alt="Full Image" />
                    <!-- Caption and description for the full image -->
                    <div id="modalCaption" class="caption"></div>
                    <div id="modalDescription" class="caption"></div>
                </div>
            </div>
            <!-- Grid for displaying thumbnail images -->
            <div class="row g-1">
                {% for item in page_obj %}
                    <div class="col-md-4">
                        <div class="grid-item fade-in" style="height: 275px;">
                            <!-- Thumbnail image with data attributes for full image, title, and description -->
                            <img class="thumbnail"
                                 id="thumbnail"
                                 src="{{ item.image.url }}"
                                 data-full-image="{{ item.image.url }}"
                                 data-title="{{ item.image_title }}"
                                 data-description="{{ item.description }}"
                                 onclick="openModal(this)">
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Pagination Links -->
            <div class="pagination justify-content-center mt-3 pagination-container">
                <!-- Previous page link -->
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="page-link mr-2">&lt;&lt;</a>
                    <a href="?page={{ page_obj.previous_page_number }}"
                       class="page-link mr-2">&lt;</a>
                {% else %}
                    <span class="page-link mr-2 disabled-pagination">&lt;&lt;</span>
                    <span class="page-link mr-2 disabled-pagination">&lt;</span>
                {% endif %}
                <!-- Numbered page links -->
                {% if page_obj.paginator.num_pages > 3 %}
                    {% if page_obj.number > 2 %}
                        <a href="?page=1" class="page-link ml-2">1</a>
                        <span class="page-link">...</span>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if num == page_obj.number %}
                            <span class="page-link current disabled-pagination">{{ num }}</span>
                        {% elif num >= page_obj.number|add:"-1" and num <= page_obj.number|add:"1" %}
                            <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.number < page_obj.paginator.num_pages|add:"-1" %}
                        <span class="page-link">...</span>
                        <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">{{ page_obj.paginator.num_pages }}</a>
                    {% endif %}
                {% else %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if num == page_obj.number %}
                            <span class="page-link current">{{ num }}</span>
                        {% else %}
                            <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <!-- Next page link -->
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link ml-2">&gt;</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"
                       class="page-link ml-2">&gt;&gt;</a>
                {% else %}
                    <span class="page-link ml-2 disabled-pagination">&gt;</span>
                    <span class="page-link ml-2 disabled-pagination">&gt;&gt;</span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}
{% block jsfiles %}
    <!-- Include JavaScript file specific to this page -->
    <script src="{% static 'gallery/js/gallery.js' %}"></script>
{% endblock jsfiles %}

home/templates/home/home.html
{% extends "snippets/base.html" %}
{% load static %}
{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}" />
{% endblock cssfiles %}
{% block content %}
    <div class="py-4 text-center welcome-container d-flex justify-content-center">
        <div class="row py-lg-5 welcome-row d-flex justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10 mx-auto welcome-column">
                <h1 class="text-center fw-light">Welcome to</h1>
                <h1 class="text-center fw-light">Tailored Donuts!</h1>
                <div class="col-10 mx-auto text-center">
                    <img class="home-page-logo img-fluid"
                         src="{% static '/images/navbar_logo_modified.png' %}"
                         alt="Tailored Donuts Logo">
                </div>
                <p class="text-center fw-light lh-md about-text">
                    Enjoy our timeless selection of gluten and dairy-sensitive baked goods, meticulously crafted to accommodate your dietary requirements. We take great pride in our role as a distinguished catering service headquartered in Middle Tennessee, serving since 2020.
                </p>
            </div>
        </div>
    </div>
    <div class="container d-flex justify-content-center">
        <div class="mt-5 about-container text-md-lg">
            <div class="row d-flex justify-content-center">
                <div class="col text-md-lg">
                    <h1 class="text-center fw-light">Our Story</h1>
                    <hr>
                    <img src="{% static 'home/images/about-taylor.jpeg' %}"
                         class="about-image"
                         alt="About Taylor" />
                    <p class="fw-light font-italic lh-lg fade-in">
                        Welcome to Tailored Donuts, where every bite is a delightful adventure! Picture this: fluffy clouds of goodness, swirling with flavors that dance on your taste buds. It all began in 2005, when our founder, Taylor, discovered a magical passion for crafting mouthwatering desserts while baking alongside her family. From that moment, our mission was clear: to revolutionize the world of donuts with a dash of fun and a sprinkle of health-conscious joy!
                    </p>
                    <p class="fw-light font-italic lh-lg fade-in">
                        At Tailored Donuts, we're all about crafting treats that are not just delicious, but also good for you. We handpick only the finest organic, unprocessed ingredients, ensuring that each bite is a harmonious blend of satisfaction and nourishment. No more sugar crashes – just guilt-free indulgence and pure joy in every flavor-packed bite!
                    </p>
                    <p class="fw-light font-italic lh-lg fade-in">
                        Located in the heart of Murfreesboro, Tennessee, we're not just a bakery; we're your go-to destination for special events and pop-up donut delights. Whether you're celebrating life's milestones or simply craving a scrumptious treat, our wholesome creations are here to elevate your experience and make every moment sweeter.
                    </p>
                    <p class="fw-light font-italic lh-lg fade-in">
                        Join us on a flavorful journey where taste meets wellness, and let's make every bite an unforgettable celebration – together at Tailored Donuts!
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block jsfiles %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock jsfiles %}

inquiry/templates/inquiry/inquiry-form.html
{% extends "snippets/base.html" %}
{% load static %}
{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'inquiry/css/inquiry-form.css' %}" />
{% endblock cssfiles %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success alert-dismissible fade show text-center success-message"
             role="alert">
            {% for message in messages %}{{ message }}{% endfor %}
        </div>
    {% endif %}
    <div class="container d-flex justify-content-center form-container">
        <div class="col-sm col-md">
            <h1 class="fw-light text-center">Contact Us</h1>
            <div class="font-italic fw-light text-center lh-md">Drop Us a Note or Inquire About Catering Services!</div>
            <div class="font-italic fw-light text-center lh-md disclaimer">
                <p>
                    <strong>Note:</strong> All requests are like a batch of our finest donuts - handled one at a time to ensure the best quality! Please bear with us and allow up to 72 hours for us to get back to you. Your patience is the secret ingredient to our sweet success!
                </p>
            </div>
            <form method="post"
                  id="contact-form"
                  action="{% url 'inquiry:submit_inquiry_url' %}">
                <br>
                {% csrf_token %}
                <fieldset>
                    <legend class="fw-light h3">
                        Contact Info:
                        <p class="text-muted" style="font-size: 0.75rem">(required)</p>
                    </legend>
                    <div class="form-row mb-3">
                        <div class="form-group col">
                            <input type="text"
                                   class="form-control form-input rounded-0"
                                   id="first-name"
                                   name="first-name"
                                   placeholder=" "
                                   required />
                            <label for="first-name" class="required-field text-muted">First Name</label>
                        </div>
                        <div class="form-group col">
                            <input type="text"
                                   class="form-control form-input rounded-0"
                                   id="last-name"
                                   name="last-name"
                                   placeholder=" "
                                   required />
                            <label for="last-name" class="required-field text-muted">Last Name</label>
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="form-group col">
                            <input type="text"
                                   class="form-control form-input rounded-0"
                                   id="phone-number"
                                   name="phone-number"
                                   placeholder=" "
                                   required
                                   pattern="[0-9]{1}-[0-9]{3}-[0-9]{3}-[0-9]{4}|[0-9]{3}-[0-9]{3}-[0-9]{4}" />
                            <label for="phone-number" class="required-field text-muted">Phone Number</label>
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="form-group col">
                            <input type="email"
                                   class="form-control form-input rounded-0"
                                   id="email"
                                   name="email"
                                   placeholder=" "
                                   required
                                   pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" />
                            <label for="email" class="required-field text-muted">Email</label>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend class="fw-light h3">
                        Message:
                        <p class="text-muted" style="font-size: 0.75rem">(required)</p>
                    </legend>
                    <div class="form-row mb-4">
                        <div class="form-group col">
                            <select class="form-control form-input rounded-0"
                                    id="subject"
                                    name="subject"
                                    required>
                                <option value="" disabled selected>Select a subject</option>
                                <option value="General">General</option>
                                <option value="Catering Request">Catering Request</option>
                                <option value="Feedback">Feedback</option>
                                <option value="Other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-row mb-3">
                        <div class="form-group col">
                            <textarea class="form-control form-input rounded-0 message-textarea"
                                      id="special-requests"
                                      name="special-requests"
                                      placeholder=""
                                      required></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="row">
                    <div class="col-md-8">
                        <button type="submit" class="btn btn-primary submit-button">Send</button>
                    </div>
                </div>
            </form>
            <br>
        </div>
    </div>
    <script></script>
{% endblock content %}
{% block jsfiles %}
    <script src="{% static 'inquiry/js/inquiry-form.js' %}"></script>
{% endblock jsfiles %}

templates/snippets/footer_snippet.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css"
      rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet">
<footer class="footer text-center text-lg-start">
    <div class="container">
        <div class="d-flex justify-content-center py-3">
            <a href="https://www.facebook.com/p/Tailored-Donuts-100064155580225/"
               target="_blank">
                <button type="button"
                        class="btn btn-primary btn-lg btn-floating mx-2 footer-button">
                    <i class="fab fa-facebook-f"></i>
                </button>
            </a>
            <a href="https://www.instagram.com/tailoreddonuts/" target="_blank">
                <button type="button"
                        class="btn btn-primary btn-lg btn-floating mx-2 footer-button">
                    <i class="fab fa-instagram"></i>
                </button>
            </a>
        </div>
        <p class="text-center text-muted">Murfreesboro, TN 37129</p>
        <p class="text-center no-underline">
            © <a class="text-center text-muted" href="{% url 'home:home' %}">Tailored Donuts</a>
        </p>
    </div>
</footer>

templates/snippets/navbar_snippet.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav class="navbar navbar-expand-lg navbar-container" data-bs-theme="dark">
    <div class="container-fluid">
        <!-- Mobile logo -->
        <a class="navbar-brand d-lg-none" href="{% url 'home:home' %}">
            <img class="navbar-logo"
                 src="{% static '/images/navbar_logo_modified.png' %}" />
        </a>
        <!-- Desktop logo -->
        <a class="navbar-brand d-none d-lg-block" href="{% url 'home:home' %}">
            <img class="navbar-logo"
                 src="{% static '/images/navbar_logo_modified.png' %}" />
        </a>
        <!-- Navbar Toggler -->
        <button class="navbar-toggler custom-toggler-button"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarContent"
                aria-controls="navbarContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <div class="navbar-toggler-icon">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <!-- Navbar Links -->
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link navbar-anchor {% if request.path == '/' %}active{% endif %}"
                       href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-anchor {% if request.path == '/inquiry/' %}active{% endif %}"
                       href="{% url 'inquiry:inquiry_url' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-anchor {% if request.path == '/locator/' %}active{% endif %}"
                       href="{% url 'locator:locator_url' %}">Find Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-anchor {% if request.path == '/gallery/' %}active{% endif %}"
                       href="{% url 'gallery:gallery_url' %}">Gallery</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block jsfiles %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
{% endblock jsfiles %}